local clue = require('mini.clue')

clue.setup({
	clues = {
		clue.gen_clues.builtin_completion(),
		clue.gen_clues.g(),
		clue.gen_clues.marks(),
		clue.gen_clues.registers(),
		clue.gen_clues.windows({ submode_resize = true }),
		clue.gen_clues.z(),
	},
	triggers = {
		{ mode = 'n', keys = '<Leader>' },
		{ mode = 'x', keys = '<Leader>' },
		{ mode = 'n', keys = [[\]] },
		{ mode = 'n', keys = '[' },
		{ mode = 'n', keys = ']' },
		{ mode = 'x', keys = '[' },
		{ mode = 'x', keys = ']' },
		{ mode = 'i', keys = '<C-x>' },
		{ mode = 'n', keys = 'g' },
		{ mode = 'x', keys = 'g' },
		{ mode = 'n', keys = "'" },
		{ mode = 'n', keys = '`' },
		{ mode = 'x', keys = "'" },
		{ mode = 'x', keys = '`' },
		{ mode = 'n', keys = '"' },
		{ mode = 'x', keys = '"' },
		{ mode = 'i', keys = '<C-r>' },
		{ mode = 'c', keys = '<C-r>' },
		{ mode = 'n', keys = '<C-w>' },
		{ mode = 'n', keys = 'z' },
		{ mode = 'x', keys = 'z' },
	},
	window = {
		delay = 50,
		config = {
			border = 'rounded',
			col = 'auto',
			height = vim.api.nvim_win_get_height(0),
			relative = 'editor',
			row = 'auto',
			width = 'auto',
		},
	},
})
