-- colors/crepuscular_dusk.lua
local api = vim.api
local cmd = vim.cmd
local opt = vim.opt

local colors = {
	-- content here will not be touched
	-- PATCH_OPEN
Normal = {fg = "#FAEFE5", bg = "#170C21"},
NormalNC = {link = "Normal"},
NotifyBackground = {link = "Normal"},
StatusLine = {link = "Normal"},
Altfont = {altfont = true, nocombine = true},
Background = {fg = "#170C21"},
BackgroundBG = {bg = "#170C21"},
BackgroundSpecial = {sp = "#170C21"},
Black = {fg = "#170C21"},
BlackBG = {bg = "#170C21"},
BlackSpecial = {sp = "#170C21"},
BlinkCmpGhostTest = {fg = "#2D203D", nocombine = true, underdotted = true},
BlinkCmpKind = {fg = "#150E1C", bg = "#B8B5B7", blend = 20},
BlinkCmpKindClass = {fg = "#170C21", bg = "#A9B4E7"},
BlinkCmpKindColor = {fg = "#D5ACB1", bg = "None"},
BlinkCmpKindConstant = {fg = "#170C21", bg = "#A5BCA8"},
BlinkCmpKindConstructor = {fg = "#170C21", bg = "#F5F1E2", sp = "#C7A9EC", nocombine = true, underdotted = true},
BlinkCmpKindCopilot = {fg = "#170C21", bg = "#F5F1E2"},
BlinkCmpKindEnum = {fg = "#170C21", bg = "#96BEB9", sp = "#F7A179", bold = true, nocombine = true, underline = true},
BlinkCmpKindEnumMember = {fg = "#170C21", bg = "#A4BBB8"},
BlinkCmpKindEvent = {fg = "#170C21", bg = "#BDB1CD", bold = true, italic = true, nocombine = true},
BlinkCmpKindField = {fg = "#170C21", bg = "#C0B2BE"},
BlinkCmpKindFile = {fg = "#170C21", bg = "#A5BCA8"},
BlinkCmpKindFolder = {fg = "#170C21", bg = "#A7BBA9", bold = true, nocombine = true, underline = true},
BlinkCmpKindFunction = {fg = "#170C21", bg = "#9BB6F0"},
BlinkCmpKindInterface = {fg = "#170C21", bg = "#ABBC90"},
BlinkCmpKindKeyword = {fg = "#170C21", bg = "#BDB1CD", bold = true, nocombine = true},
BlinkCmpKindMethod = {fg = "#170C21", bg = "#ABB7CB", nocombine = true, underdotted = true},
BlinkCmpKindModule = {fg = "#170C21", bg = "#E6A88A", bold = true, nocombine = true},
BlinkCmpKindOperator = {fg = "#170C21", bg = "#6AC5BD"},
BlinkCmpKindProperty = {fg = "#170C21", bg = "#C9B392"},
BlinkCmpKindReference = {fg = "#170C21", bg = "#E9AB32"},
BlinkCmpKindSnippet = {fg = "#170C21", bg = "#FF9F5A"},
BlinkCmpKindStruct = {fg = "#170C21", bg = "#ABBC90", bold = true, nocombine = true},
BlinkCmpKindText = {fg = "#170C21", bg = "#FAEFE5", italic = true, nocombine = true},
BlinkCmpKindTypeParameter = {fg = "#170C21", bg = "#A7BBA9", nocombine = true, underdotted = true},
BlinkCmpKindUnit = {fg = "#170C21", bg = "#F99D9D"},
BlinkCmpKindValue = {fg = "#170C21", bg = "#E0A8A9"},
BlinkCmpKindVariable = {fg = "#170C21", bg = "#C4A9F3"},
BlinkCmpLabel = {fg = "#FAEFE5"},
BlinkCmpLabelDeprecated = {fg = "#E9AB32", strikethrough = true},
BlinkCmpLabelMatch = {fg = "#A7BBA9", bold = true},
BlinkCmpMenu = {fg = "#6A577B", blend = 20},
BlinkCmpMenuSelection = {bg = "#3B2354", bold = true, nocombine = true},
Blue = {fg = "#A9B4E7"},
BlueBG = {bg = "#A9B4E7"},
BlueSpecial = {sp = "#A9B4E7"},
Bold = {bold = true, nocombine = true},
BoldItalic = {bold = true, italic = true, nocombine = true},
BoldItalicUndercurl = {bold = true, italic = true, nocombine = true, undercurl = true},
BoldItalicUnderdash = {bold = true, italic = true, nocombine = true, underdashed = true},
BoldItalicUnderdot = {bold = true, italic = true, nocombine = true, underdotted = true},
BoldItalicUnderline = {bold = true, italic = true, nocombine = true, underline = true},
BoldReverse = {bold = true, nocombine = true, reverse = true},
BoldUndercurl = {bold = true, nocombine = true, undercurl = true},
BoldUnderdash = {bold = true, nocombine = true, underdashed = true},
BoldUnderdot = {bold = true, nocombine = true, underdotted = true},
BoldUnderline = {bold = true, nocombine = true, underline = true},
Boolean = {fg = "#D5ACB1"},
["@boolean"] = {link = "Boolean"},
BrightBlack = {fg = "#131016"},
BrightBlackBG = {bg = "#131016"},
BrightBlackSpecial = {sp = "#131016"},
BrightBlue = {fg = "#9BB6F0"},
BrightBlueBG = {bg = "#9BB6F0"},
BrightBlueSpecial = {sp = "#9BB6F0"},
BrightCyan = {fg = "#A4BBB8"},
BrightCyanBG = {bg = "#A4BBB8"},
BrightCyanSpecial = {sp = "#A4BBB8"},
BrightGreen = {fg = "#ABBC90"},
BrightGreenBG = {bg = "#ABBC90"},
BrightGreenSpecial = {sp = "#ABBC90"},
BrightGrey = {fg = "#C0B2BE"},
BrightGreyBG = {bg = "#C0B2BE"},
BrightGreySpecial = {sp = "#C0B2BE"},
BrightOrange = {fg = "#FF9F5A"},
BrightOrangeBG = {bg = "#FF9F5A"},
BrightOrangeSpecial = {sp = "#FF9F5A"},
BrightPurple = {fg = "#C4A9F3"},
BrightPurpleBG = {bg = "#C4A9F3"},
BrightPurpleSpecial = {sp = "#C4A9F3"},
BrightRed = {fg = "#F99D9D"},
BrightRedBG = {bg = "#F99D9D"},
BrightRedSpecial = {sp = "#F99D9D"},
BrightWhite = {fg = "#F5F1E2"},
BrightWhiteBG = {bg = "#F5F1E2"},
BrightWhiteSpecial = {sp = "#F5F1E2"},
BrightYellow = {fg = "#E9AB32"},
BrightYellowBG = {bg = "#E9AB32"},
BrightYellowSpecial = {sp = "#E9AB32"},
Character = {fg = "#A4BBB8"},
["@character"] = {link = "Character"},
CmpItemAbbr = {fg = "#FAEFE5", blend = 20, nocombine = true},
CmpItemAbbrDeprecated = {fg = "#E9AB32", blend = 20},
CmpItemAbbrMatch = {fg = "#A7BBA9", blend = 20, bold = true, nocombine = true},
CmpItemAbbrMatchFuzzy = {fg = "#E6A88A", blend = 20, bold = true, nocombine = true},
CmpItemKind = {fg = "#150E1C", bg = "#B8B5B7", blend = 20},
CmpItemKindClass = {fg = "#170C21", bg = "#A9B4E7"},
CmpItemKindColor = {fg = "#D5ACB1", bg = "None"},
CmpItemKindConstant = {fg = "#170C21", bg = "#A5BCA8"},
CmpItemKindConstructor = {fg = "#170C21", bg = "#F5F1E2", sp = "#C7A9EC", nocombine = true, underdotted = true},
CmpItemKindCopilot = {fg = "#170C21", bg = "#F5F1E2"},
CmpItemKindEnum = {fg = "#170C21", bg = "#96BEB9", sp = "#F7A179", bold = true, nocombine = true, underline = true},
CmpItemKindEnumMember = {fg = "#170C21", bg = "#A4BBB8"},
CmpItemKindEvent = {fg = "#170C21", bg = "#BDB1CD", bold = true, italic = true, nocombine = true},
CmpItemKindField = {fg = "#170C21", bg = "#C0B2BE"},
CmpItemKindFile = {fg = "#170C21", bg = "#A5BCA8"},
CmpItemKindFolder = {fg = "#170C21", bg = "#A7BBA9", bold = true, nocombine = true, underline = true},
CmpItemKindFunction = {fg = "#170C21", bg = "#9BB6F0"},
CmpItemKindInterface = {fg = "#170C21", bg = "#ABBC90"},
CmpItemKindKeyword = {fg = "#170C21", bg = "#BDB1CD", bold = true, nocombine = true},
CmpItemKindMethod = {fg = "#170C21", bg = "#ABB7CB", nocombine = true, underdotted = true},
CmpItemKindModule = {fg = "#170C21", bg = "#E6A88A", bold = true, nocombine = true},
CmpItemKindOperator = {fg = "#170C21", bg = "#6AC5BD"},
CmpItemKindProperty = {fg = "#170C21", bg = "#C9B392"},
CmpItemKindReference = {fg = "#170C21", bg = "#E9AB32"},
CmpItemKindSnippet = {fg = "#170C21", bg = "#FF9F5A"},
CmpItemKindStruct = {fg = "#170C21", bg = "#ABBC90", bold = true, nocombine = true},
CmpItemKindText = {fg = "#170C21", bg = "#FAEFE5", italic = true, nocombine = true},
CmpItemKindTypeParameter = {fg = "#170C21", bg = "#A7BBA9", nocombine = true, underdotted = true},
CmpItemKindUnit = {fg = "#170C21", bg = "#F99D9D"},
CmpItemKindValue = {fg = "#170C21", bg = "#E0A8A9"},
CmpItemKindVariable = {fg = "#170C21", bg = "#C4A9F3"},
CmpItemMenu = {fg = "#6A577B", blend = 20, italic = true, nocombine = true},
ColorColumn = {bg = "#1C1027"},
Comment = {fg = "#6A577B", italic = true, nocombine = true},
["@comment"] = {link = "Comment"},
["@text.literal"] = {link = "Comment"},
Conceal = {fg = "#2E1F3D"},
Conditional = {fg = "#F99D9D"},
["@conditional"] = {link = "Conditional"},
Constant = {fg = "#A5BCA8"},
["@constant"] = {link = "Constant"},
CurSearch = {bg = "#3B2741"},
Cursor = {nocombine = true, reverse = true},
CursorIM = {link = "Cursor"},
lCursor = {link = "Cursor"},
CursorColumn = {bg = "#1C1027"},
CursorLine = {bg = "#1C1027"},
CursorLineNr = {fg = "#C4A9F3", bg = "#1C1027"},
CursorLineFold = {link = "CursorLineNr"},
Cyan = {fg = "#6AC5BD"},
CyanBG = {bg = "#6AC5BD"},
CyanSpecial = {sp = "#6AC5BD"},
Debug = {fg = "#A4BBB8", sp = "#6AC5BD", nocombine = true, underdashed = true},
["@debug"] = {link = "Debug"},
Define = {fg = "#96BEB9"},
["@constant.macro"] = {link = "Define"},
["@define"] = {link = "Define"},
Delimiter = {fg = "#F7B866"},
["@punctuation"] = {link = "Delimiter"},
DiagnosticError = {fg = "#F99D9D", bg = "#37151A"},
DiagnosticFloatingError = {fg = "#D5ACB1"},
DiagnosticFloatingHint = {fg = "#ABB7CB"},
DiagnosticFloatingInfo = {fg = "#BDB1CD"},
DiagnosticFloatingOk = {fg = "#A5BCA8"},
DiagnosticFloatingWarn = {fg = "#C9B392"},
DiagnosticHint = {fg = "#9BB6F0", bg = "#17202D"},
DiagnosticInfo = {fg = "#C4A9F3", bg = "#281937"},
DiagnosticOk = {fg = "#ABBC90", bg = "#142316"},
DiagnosticSignError = {fg = "#F99D9D"},
DiagnosticSignHint = {fg = "#9BB6F0"},
DiagnosticSignInfo = {fg = "#C4A9F3"},
DiagnosticSignOk = {fg = "#ABBC90"},
DiagnosticSignWarn = {fg = "#E9AB32"},
DiagnosticUnderlineError = {sp = "#F99D9D", nocombine = true, undercurl = true},
DiagnosticUnderlineHint = {sp = "#9BB6F0", nocombine = true, undercurl = true},
DiagnosticUnderlineInfo = {sp = "#C4A9F3", nocombine = true, undercurl = true},
DiagnosticUnderlineOk = {sp = "#ABBC90", nocombine = true, undercurl = true},
DiagnosticUnderlineWarn = {sp = "#E9AB32", nocombine = true, undercurl = true},
DiagnosticVirtualTextError = {fg = "#F99D9D", bg = "#37151A", italic = true, nocombine = true},
DiagnosticVirtualTextHint = {fg = "#9BB6F0", bg = "#17202D", italic = true, nocombine = true},
DiagnosticVirtualTextInfo = {fg = "#C4A9F3", bg = "#281937", italic = true, nocombine = true},
DiagnosticVirtualTextOk = {fg = "#ABBC90", bg = "#142316", italic = true, nocombine = true},
DiagnosticVirtualTextWarn = {fg = "#E9AB32", bg = "#251F14", italic = true, nocombine = true},
DiagnosticWarn = {fg = "#E9AB32", bg = "#251F14"},
DiffAdd = {bg = "#171B12", sp = "#ABBC90"},
NeogitDiffAddHighlight = {link = "DiffAdd"},
DiffChange = {bg = "#432F07", bold = true, italic = true, nocombine = true},
NeogitDiffContextHighlight = {link = "DiffChange"},
DiffDelete = {fg = "#4A2946", bg = "#2B0202"},
NeogitDiffDeleteHighlight = {link = "DiffDelete"},
DiffText = {bg = "#252B2A", sp = "#C4A9F3", nocombine = true, underdotted = true},
DimBlack = {fg = "#150E1C"},
DimBlackBG = {bg = "#150E1C"},
DimBlackSpecial = {sp = "#150E1C"},
DimBlue = {fg = "#ABB7CB"},
DimBlueBG = {bg = "#ABB7CB"},
DimBlueSpecial = {sp = "#ABB7CB"},
DimCyan = {fg = "#96BEB9"},
DimCyanBG = {bg = "#96BEB9"},
DimCyanSpecial = {sp = "#96BEB9"},
DimGreen = {fg = "#A5BCA8"},
DimGreenBG = {bg = "#A5BCA8"},
DimGreenSpecial = {sp = "#A5BCA8"},
DimGrey = {fg = "#B8B5B7"},
DimGreyBG = {bg = "#B8B5B7"},
DimGreySpecial = {sp = "#B8B5B7"},
DimOrange = {fg = "#E6A88A"},
DimOrangeBG = {bg = "#E6A88A"},
DimOrangeSpecial = {sp = "#E6A88A"},
DimPurple = {fg = "#BDB1CD"},
DimPurpleBG = {bg = "#BDB1CD"},
DimPurpleSpecial = {sp = "#BDB1CD"},
DimRed = {fg = "#D5ACB1"},
DimRedBG = {bg = "#D5ACB1"},
DimRedSpecial = {sp = "#D5ACB1"},
DimWhite = {fg = "#FAEFE5"},
DimWhiteBG = {bg = "#FAEFE5"},
DimWhiteSpecial = {sp = "#FAEFE5"},
DimYellow = {fg = "#C9B392"},
DimYellowBG = {bg = "#C9B392"},
DimYellowSpecial = {sp = "#C9B392"},
Directory = {fg = "#9BB6F0"},
EndOfBuffer = {fg = "#2E1F3D"},
Error = {fg = "#131016", bg = "#F99D9D"},
ErrorMsg = {fg = "#F99D9D"},
Exception = {fg = "#F99D9D", nocombine = true, underdashed = true},
["@exception"] = {link = "Exception"},
EyelinerPrimary = {fg = "#6AC5BD", sp = "#FF9F5A", nocombine = true, underdashed = true},
EyelinerSecondary = {fg = "#96BEB9", sp = "#E6A88A", nocombine = true, underdashed = true},
Float = {fg = "#EEA83F"},
["@float"] = {link = "Float"},
FloatBorder = {fg = "#B8B5B7"},
FloatTitle = {fg = "#C0B2BE"},
FoldColumn = {fg = "#BDB1CD", bg = "#1C1027"},
Folded = {fg = "#BDB1CD"},
Foreground = {fg = "#FAEFE5"},
ForegroundBG = {bg = "#FAEFE5"},
ForegroundSpecial = {sp = "#FAEFE5"},
Function = {fg = "#9BB6F0", bold = true, italic = true, nocombine = true},
["@function"] = {link = "Function"},
["@method"] = {link = "Function"},
GitSignsAdd = {fg = "#ABBC90", bg = "#1C1027", nocombine = true},
GitSignsAddNr = {fg = "#A5BCA8", bg = "#1C1027", nocombine = true},
GitSignsChange = {fg = "#9BB6F0", bg = "#1C1027", nocombine = true},
GitSignsChangeNr = {fg = "#ABB7CB", bg = "#1C1027", nocombine = true},
GitSignsChangedelete = {fg = "#E9AB32", bg = "#1C1027", nocombine = true},
GitSignsChangedeleteNr = {fg = "#C9B392", bg = "#1C1027", nocombine = true},
GitSignsDelete = {fg = "#F99D9D", bg = "#1C1027", nocombine = true},
GitSignsDeleteNr = {fg = "#D5ACB1", bg = "#1C1027", nocombine = true},
GitSignsTopdelete = {fg = "#F99D9D", bg = "#1C1027", nocombine = true},
GitSignsTopdeleteNr = {fg = "#D5ACB1", bg = "#1C1027", nocombine = true},
GitSignsUntracked = {fg = "#FF9F5A", bg = "#1C1027", nocombine = true},
GitSignsUntrackedNr = {fg = "#E6A88A", bg = "#1C1027", nocombine = true},
Green = {fg = "#A7BBA9"},
GreenBG = {bg = "#A7BBA9"},
GreenSpecial = {sp = "#A7BBA9"},
Grey = {fg = "#B8B5B7"},
GreyBG = {bg = "#B8B5B7"},
GreySpecial = {sp = "#B8B5B7"},
Identifier = {fg = "#C7A9EC"},
["@namespace"] = {link = "Identifier"},
["@parameter"] = {link = "Identifier"},
["@text.reference"] = {link = "Identifier"},
["@variable"] = {link = "Identifier"},
Ignore = {fg = "#170C21"},
IncSearch = {fg = "#170C21", bg = "#A7BBA9"},
Include = {fg = "#C9B392"},
["@include"] = {link = "Include"},
Italic = {italic = true, nocombine = true},
ItalicReverse = {italic = true, nocombine = true, reverse = true},
ItalicUndercurl = {italic = true, nocombine = true, undercurl = true},
ItalicUnderdash = {italic = true, nocombine = true, underdashed = true},
ItalicUnderdot = {italic = true, nocombine = true, underdotted = true},
ItalicUnderline = {italic = true, nocombine = true, underline = true},
Keyword = {fg = "#BDB1CD"},
["@keyword"] = {link = "Keyword"},
Label = {fg = "#C9B392"},
["@label"] = {link = "Label"},
LineNr = {fg = "#4F3960", bg = "#1C1027"},
LineNrAbove = {fg = "#4D3A5F"},
LineNrBelow = {fg = "#4D3A5F"},
LspCodeLens = {fg = "#ABB7CB"},
LspCodeLensSeparator = {fg = "#C0B2BE"},
LspInlayHint = {fg = "#41433D", italic = true, nocombine = true, underdotted = true},
LspReferenceRead = {fg = "#BDB1CD"},
LspReferenceText = {fg = "#C7A9EC"},
LspReferenceWrite = {fg = "#A9B4E7"},
LspSignatureActiveParameter = {fg = "#6AC5BD", nocombine = true, underdouble = true},
Macro = {fg = "#BDB1CD"},
["@function.macro"] = {link = "Macro"},
["@macro"] = {link = "Macro"},
MatchParen = {fg = "#E9AB32"},
ModeMsg = {fg = "#B8B5B7"},
MoreMsg = {fg = "#C9B392"},
MsgArea = {fg = "#FAEFE5"},
MsgSeparator = {fg = "#B8B5B7"},
NeogitHunkHeader = {fg = "#C4A9F3", bg = "#150E1C", nocombine = true},
NeogitHunkHeaderHighlight = {fg = "#C4A9F3", bg = "#150E1C", bold = true, nocombine = true, underline = true},
NeotestAdapterName = {fg = "#C7A9EC", bold = true, nocombine = true},
NeotestBorder = {fg = "#C4A9F3", nocombine = true},
NeotestCanvas = {fg = "#B8B5B7", nocombine = true},
NeotestDir = {fg = "#EEA83F", nocombine = true},
NeotestExpandMarker = {fg = "#B8B5B7", nocombine = true},
NeotestFailed = {fg = "#E0A8A9", bold = true, nocombine = true},
NeotestFile = {fg = "#A7BBA9", italic = true, nocombine = true},
NeotestFocused = {bg = "#131016", nocombine = true},
NeotestIndent = {fg = "#170C21", nocombine = true},
NeotestMarked = {fg = "#F7A179", bold = true, nocombine = true, underdotted = true},
NeotestNamespace = {fg = "#C4A9F3", nocombine = true},
NeotestPassed = {fg = "#ABBC90", bold = true, nocombine = true},
NeotestRunning = {fg = "#EEA83F", nocombine = true, underdashed = true},
NeotestSkipped = {fg = "#FF9F5A", nocombine = true, underdotted = true},
NeotestTarget = {fg = "#6AC5BD", nocombine = true},
NeotestTest = {fg = "#A9B4E7", bold = true, nocombine = true},
NeotestUnknown = {fg = "#B8B5B7", italic = true, nocombine = true},
NeotestWinSelect = {fg = "#C0B2BE", nocombine = true},
NoCombine = {nocombine = true},
NonText = {fg = "#3F2D4E"},
TelescopeBorder = {link = "NonText"},
NormalFloat = {fg = "#FAEFE5", bg = "#170C21", blend = 12},
StatusLineNC = {link = "NormalFloat"},
TelescopeNormal = {link = "NormalFloat"},
NotifyDEBUGBody = {fg = "#EDE0DA"},
NotifyDEBUGBorder = {fg = "#ABB7CB"},
NotifyDEBUGIcon = {fg = "#9BB6F0"},
NotifyDEBUGTitle = {fg = "#A9B4E7", bold = true, nocombine = true},
NotifyERRORBody = {fg = "#F4DFD1"},
NotifyERRORBorder = {fg = "#D5ACB1"},
NotifyERRORIcon = {fg = "#F99D9D"},
NotifyERRORTitle = {fg = "#E0A8A9", bold = true, nocombine = true},
NotifyINFOBody = {fg = "#EEDFDB"},
NotifyINFOBorder = {fg = "#BDB1CD"},
NotifyINFOIcon = {fg = "#C4A9F3"},
NotifyINFOTitle = {fg = "#C7A9EC", bold = true, nocombine = true},
NotifyTRACEBody = {fg = "#F7DECC"},
NotifyTRACEBorder = {fg = "#E6A88A"},
NotifyTRACEIcon = {fg = "#FF9F5A"},
NotifyTRACETitle = {fg = "#F7A179", bold = true, nocombine = true},
NotifyWARNBody = {fg = "#F7DEC7"},
NotifyWARNBorder = {fg = "#C9B392"},
NotifyWARNIcon = {fg = "#E9AB32"},
NotifyWARNTitle = {fg = "#EEA83F", bold = true, nocombine = true},
Number = {fg = "#F7A179"},
["@number"] = {link = "Number"},
Operator = {fg = "#6AC5BD"},
["@operator"] = {link = "Operator"},
Orange = {fg = "#F7A179"},
OrangeBG = {bg = "#F7A179"},
OrangeSpecial = {sp = "#F7A179"},
Pmenu = {fg = "#B8B5B7"},
PmenuExtra = {fg = "#FAEFE5"},
PmenuExtraSel = {fg = "#EEA83F"},
PmenuKind = {fg = "#170C21", bg = "#B8B5B7"},
PmenuKindSel = {bg = "#091311", blend = 30},
PmenuSbar = {fg = "#4D3A5F"},
PmenuSel = {bg = "#09130A", blend = 30},
PmenuThumb = {fg = "#B8B5B7"},
PreCondit = {fg = "#E6A88A"},
PreProc = {fg = "#C0B2BE"},
["@preproc"] = {link = "PreProc"},
Purple = {fg = "#C7A9EC"},
PurpleBG = {bg = "#C7A9EC"},
PurpleSpecial = {sp = "#C7A9EC"},
Question = {fg = "#ABB7CB"},
QuickFixLine = {fg = "#131016", bg = "#C0B2BE"},
Red = {fg = "#E0A8A9"},
RedBG = {bg = "#E0A8A9"},
RedSpecial = {sp = "#E0A8A9"},
Repeat = {fg = "#ABBC90"},
["@repeat"] = {link = "Repeat"},
Reverse = {nocombine = true, reverse = true},
Search = {bg = "#150E1C"},
SignColumn = {bg = "#1C1027"},
CursorLineSign = {link = "SignColumn"},
SnippetVirtTextChoiceActive = {fg = "#ABBC90"},
SnippetVirtTextChoicePassive = {fg = "#E9AB32"},
SnippetVirtTextChoiceSnippetPassive = {fg = "#C0B2BE"},
SnippetVirtTextChoiceUnvisited = {fg = "#9BB6F0"},
SnippetVirtTextChoiceVisited = {fg = "#C4A9F3"},
SnippetVirtTextInsertActive = {fg = "#ABBC90"},
SnippetVirtTextInsertPassive = {fg = "#E9AB32"},
SnippetVirtTextInsertSnippetPassive = {fg = "#C0B2BE"},
SnippetVirtTextInsertUnvisited = {fg = "#9BB6F0"},
SnippetVirtTextInsertVisited = {fg = "#C4A9F3"},
SnippetVirtTextSnippetActive = {fg = "#ABBC90"},
SnippetVirtTextSnippetPassive = {fg = "#E9AB32"},
SnippetVirtTextSnippetSnippetPassive = {fg = "#C0B2BE"},
SnippetVirtTextSnippetUnvisited = {fg = "#9BB6F0"},
SnippetVirtTextSnippetVisited = {fg = "#C4A9F3"},
Special = {fg = "#F5F1E2", sp = "#C7A9EC", nocombine = true, underdotted = true},
["@constant.builtin"] = {link = "Special"},
["@constructor"] = {link = "Special"},
["@function.builtin"] = {link = "Special"},
SpecialChar = {fg = "#6AC5BD", sp = "#F7A179", nocombine = true, underdouble = true},
["@character.special"] = {link = "SpecialChar"},
["@string.escape"] = {link = "SpecialChar"},
["@string.special"] = {link = "SpecialChar"},
SpecialComment = {fg = "#C69D8F", sp = "#A9B4E7", nocombine = true, underdotted = true},
SpecialKey = {fg = "#E9AB32", nocombine = true, underdouble = true},
SpellBad = {sp = "#D5ACB1", nocombine = true, underdashed = true},
SpellCap = {sp = "#6AC5BD", nocombine = true, underdashed = true},
SpellLocal = {sp = "#A7BBA9", nocombine = true, underdashed = true},
SpellRare = {sp = "#C4A9F3", nocombine = true, underdashed = true},
Standout = {nocombine = true, standout = true},
Statement = {fg = "#D5ACB1"},
WinBar = {link = "StatusLine"},
WinBarNC = {link = "StatusLineNC"},
StorageClass = {fg = "#96BEB9", italic = true, nocombine = true, underdotted = true},
["@storageclass"] = {link = "StorageClass"},
StrikeThrough = {nocombine = true, strikethrough = true},
String = {fg = "#FAEFE5"},
["@string"] = {link = "String"},
Structure = {fg = "#ABBC90", italic = true, nocombine = true, underdotted = true},
["@structure"] = {link = "Structure"},
TabLine = {bg = "#2E1F3D"},
TabLineFill = {bg = "#382747", blend = 50},
TabLineSel = {bg = "#1F122A"},
Tag = {fg = "#FF9F5A", sp = "#A9B4E7", nocombine = true, underdotted = true},
["@tag"] = {link = "Tag"},
TelescopeMatching = {fg = "#E6A88A", bold = true, nocombine = true},
TelescopePromptNormal = {link = "TelescopeNormal"},
TelescopePromptPrefix = {fg = "#786686"},
TelescopeSelection = {fg = "#ABB7CB", bg = "#293547"},
TelescopeSelectionCaret = {fg = "#F99D9D", bg = "#56262E"},
TelescopeTitle = {fg = "#A9B4E7", bold = true, nocombine = true},
TermCursor = {nocombine = true, reverse = true},
TermCursorNC = {bg = "#3B2741"},
Title = {fg = "#C0B2BE"},
["@text.title"] = {link = "Title"},
Todo = {fg = "#131016", bg = "#9BB6F0"},
["@text.todo"] = {link = "Todo"},
Type = {fg = "#A7BBA9", italic = true, nocombine = true, underdotted = true},
["@type"] = {link = "Type"},
Typedef = {fg = "#ABB7CB", italic = true, nocombine = true, underdotted = true},
["@type.definition"] = {link = "Typedef"},
Undercurl = {nocombine = true, undercurl = true},
Underdash = {nocombine = true, underdashed = true},
Underdot = {nocombine = true, underdotted = true},
Underdouble = {nocombine = true, underdouble = true},
Underline = {nocombine = true, underline = true},
Underlined = {nocombine = true, underline = true},
["@text.underline"] = {link = "Underlined"},
VertSplit = {fg = "#A198A5"},
Visual = {bg = "#41321F"},
VisualNOS = {bg = "#785832"},
WarningMsg = {fg = "#E9AB32"},
White = {fg = "#FAEFE5"},
WhiteBG = {bg = "#FAEFE5"},
WhiteSpecial = {sp = "#FAEFE5"},
Whitespace = {fg = "#4D3A5F"},
WildMenu = {fg = "#131016", bg = "#E6A88A"},
Winseparator = {fg = "#3F2D4E"},
Yellow = {fg = "#EEA83F"},
YellowBG = {bg = "#EEA83F"},
YellowSpecial = {sp = "#EEA83F"},
["@field"] = {fg = "#BDB1CD"},
["@property"] = {fg = "#BDB1CD"},
["@text.uri"] = {sp = "#9BB6F0", nocombine = true, underline = true},
	-- PATCH_CLOSE
	-- content here will not be touched
}

-- colorschemes generally want to do this
cmd.highlight('clear')
vim.g.colors_name = 'crepuscular_dusk'
opt.background = 'dark'

-- Sets the colorscheme to be Crepuscular
cmd.colorscheme(vim.g.colors_name)

-- apply highlight groups
for group, attrs in pairs(colors) do
	api.nvim_set_hl(0, group, attrs)
end
